---
apiVersion: v1
kind: Service
metadata:
  name: recipecollection-frontend
spec:
  type: ClusterIP
  selector:
    app: recipecollection-frontend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
